// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Role.
const (
	Admin   Role = "admin"
	Manager Role = "manager"
	Student Role = "student"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Manager:
		return true
	case Student:
		return true
	default:
		return false
	}
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Password string `json:"password"`

	// Userid Example: student001
	Userid string `json:"userid"`
}

// Error 統一エラー封筒 (api.md Conventions)
type Error struct {
	Error struct {
		// Code snake_case の機械可読文字列
		//
		// Example: validation_failed
		Code string `json:"code"`

		// Message 開発者向けの英語文。UI にそのまま表示しない
		Message string `json:"message"`
	} `json:"error"`
}

// Role User Account の権限レベル (CONTEXT.md「Role」)
type Role string

// User defines model for User.
type User struct {
	// Id opaque な UUID 文字列
	Id openapi_types.UUID `json:"id"`

	// Name Example: 山田 太郎
	Name string `json:"name"`

	// Role User Account の権限レベル (CONTEXT.md「Role」)
	Role Role `json:"role"`

	// Userid Example: student001
	Userid string `json:"userid"`
}

// InternalError 統一エラー封筒 (api.md Conventions)
type InternalError = Error

// Unauthorized 統一エラー封筒 (api.md Conventions)
type Unauthorized = Error

// ValidationError 統一エラー封筒 (api.md Conventions)
type ValidationError = Error

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMe 現在の User Account を返す
	// (GET /api/me)
	GetMe(ctx echo.Context) error
	// DeleteSession 現在のセッションを削除する (ログアウト)
	// (DELETE /api/session)
	DeleteSession(ctx echo.Context) error
	// CreateSession セッションを作成する (ログイン)
	// (POST /api/session)
	CreateSession(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// DeleteSession converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSession(ctx)
	return err
}

// CreateSession converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSession(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSession(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(options.BaseURL+"/api/session", wrapper.DeleteSession, options.OperationMiddlewares["deleteSession"]...)
	router.POST(options.BaseURL+"/api/session", wrapper.CreateSession, options.OperationMiddlewares["createSession"]...)
	router.GET(options.BaseURL+"/api/me", wrapper.GetMe, options.OperationMiddlewares["getMe"]...)

}

type InternalErrorJSONResponse Error

type UnauthorizedJSONResponse Error

type ValidationErrorJSONResponse Error

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200ResponseHeaders struct {
	SetCookie *string
}

type GetMe200JSONResponse struct {
	Body    User
	Headers GetMe200ResponseHeaders
}

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMe500JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessionRequestObject struct {
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204ResponseHeaders struct {
	SetCookie *string
}

type DeleteSession204Response struct {
	Headers DeleteSession204ResponseHeaders
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type DeleteSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteSession500JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession200ResponseHeaders struct {
	SetCookie *string
}

type CreateSession200JSONResponse struct {
	Body    User
	Headers CreateSession200ResponseHeaders
}

func (response CreateSession200JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSession401JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreateSession422JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateSession500JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetMe 現在の User Account を返す
	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// DeleteSession 現在のセッションを削除する (ログアウト)
	// (DELETE /api/session)
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)
	// CreateSession セッションを作成する (ログイン)
	// (POST /api/session)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(ctx echo.Context) error {
	var request DeleteSessionRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx.Request().Context(), request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		return validResponse.VisitDeleteSessionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(ctx echo.Context) error {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx.Request().Context(), request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		return validResponse.VisitCreateSessionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFdtbxPHFv4ro7n3QyI5sRNyv1jiQ25A90aFgghpK1GEht1JsmDPLjtrSoos7c4CcULSBAS4aVNSwE0d",
	"U+dFlBJICj/mZG3nX1Qz63cbQitov00mO+ecec7zPHN8HWtm0jIZZQ7H8evYptwyGafqj1HmUJuRxHHb",
	"Nm25oZnMocyRS2JZCUMjjmGy6CVuMrnHtSmaJHL1b5tO4Dj+V7QRPRr+l0fDaOl0OoJ1yjXbsGQQHMcg",
	"noO/B/4S+HvBrZsHfh5EHvx18PdwOoLHGUk5U6ZtfE31j19MaaVQKSxU8nvgChC74PsgXoD/M/jPwCuA",
	"lwV/t7SyerC8FGRmQMyDv6vZVKfMMUgC7e8slIpPZNWfkYShq8r+LhQlfgXwZySWtZKD3HbpfhbLr6sB",
	"ZPwRmxKHjlHODZOdoVdSlKuqLNu0qO0YIQsswvlXpq0wnzDtJHFwvLEZwUmDnaBs0pnC8YEIdqYtiuOY",
	"O7bBJiUAKU5tQx2m10jSSoT/TUmkYrGBw86nI9imV1KGLXt+rhYs0sh/vn7EvHiJao5MWUe6FZny8+39",
	"HbfOqWDLKxfvoh5iGf1JHY2Y7Krsnsl4r0zQggGtRWzd1kyddubhjFymFzTCKQJvo7S+Wnq8FSxuVgrF",
	"0oOZoJgNMlkcaULjap0iFyaIkaDyfh0wJinnZLJLtoMHt8vLryruzWDpDnh3wNuo3N6uFB6WHsyAK8ZH",
	"EXhPwfsBvA3wXoP3uvIoX869kgSWNL6BD4Nc3bGRvxPvtu9DqLq15YyZ6FL/OKc2GtY0M8UchVd+/WB5",
	"CfxfwF8G/ynqGTn16dnjX5ztT+rgzssY4C7IDlGWSsqEVTLJGgkjk9TGEUz0pMGaimjgKNN1NjIkaGth",
	"pkWupGQLC2h8fPQYam5eXQeplNG1XYwkaSvng+3t8r0tFOQKB/433Y7YVXjepXoF4fuI6t09VTXXtaRq",
	"rebv2l5OtZRtONNjsooa883LBh1OSdW2A3eRaJcp0/vCduiIhwaDwjPgiv87jnWKJaZRFI3J0FQuSJKO",
	"GQ49eoJcwxFsyEDhgVqFcVwN1LgesYxP6HToggabMDtrAVGQju2vg8jJhdgB/4ky8x30Ob2IQDwGPysN",
	"09sAsVn9UG4+Az8TSgqdOT52Fg2fHgVXoPK9fKXwELw8Om0bTDOsBOUIvE3UTFOvsrZY/vVGT5vXgOuN",
	"HgPXA/FGlfMjiJdyLXNle2UQ3dR4lFtUi1ZdCbyNZmdCIO6Wik/Ay4O3DOI2uOJLhYfhKA7onPRZtik7",
	"JwvGEXyV2jyEItY/0B+T5DEtyohl4Dg+0h/rP6Lc1JlSbZVpoyFzJ6l6C6RKlDeN6jiO/0edk4orzWPC",
	"YCz2wZ41Jc8ur1p58XWwkpdoyC/AFTxh6AabrJNL+dsqCK9KM4lUcGuhki8GG9+FYOEInqJEp7aqeow6",
	"fSMhwTpYU1qZDeZehs+7jLP728H9F8oyV9tmAVTnaON+7dqTtxmKDbzt6nUsoy0TTjqC/xMC++5DrUNa",
	"s1xx/FyrUM+dT5+PYJ5KJok93QFqw4TF3cqbe+Atq2iKEjXlKaQS1OmCWXCrUC7OdpuW5kvZx+A9Ld94",
	"BN4ieGsgBBqMDTXygCtwpI1px1Sasbri2xg31E3qLXmD2bmD5VxpJwPeG3BFEyty28HcS/Dug/f9n2JF",
	"99arkCpXyDLUc5Jc6xuepEdjvYfS4q92uLOF7ai3FwV+EcSWdDaxBn6mV/LLMsN5r/Wa4buAoqg2YynT",
	"ya3IWVhKYO3tODSrTZplNdT+zkJQ/FbVmQf/jnQ9f1ON+rOVQg7EHHibwfyrIPNTfSxBPUOxAWQwNRtd",
	"aEzWvLdmea10aRllcfjaUe7819SnP5g3dR2X061vq2OnaPof8Mfwt0opsxTMrYIr2pRdU1pWPT7v0733",
	"V8VhjznqJOdHNc2hwcHDD7X/KvsQUuxU4P7vK6XMUrsC5RzSq274RwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
