import { afterEach, expect, test, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { createMemoryRouter, RouterProvider } from 'react-router-dom'
import type { components } from '@/api/schema'
import App from './App'

afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals() })

test('Apply preflights all rows, continues failures, retains passwords and exports cumulative CSV in row order', async () => {
  const created: components['schemas']['CreateUserAccountRequest'][] = []
  const blobs: Blob[] = []
  vi.spyOn(URL, 'createObjectURL').mockImplementation((blob) => { if (blob instanceof Blob) blobs.push(blob); return 'blob:test' })
  vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {})
  vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
  vi.stubGlobal('fetch', vi.fn(async (request: Request) => {
    const path = new URL(request.url).pathname
    let body: unknown = { id: '00000000-0000-0000-0000-000000000001', userid: 'admin', name: 'Admin', role: 'admin' }
    let status = 200
    if (path === '/api/admin/users' && request.method === 'POST') {
      const data: components['schemas']['CreateUserAccountRequest'] = await request.json()
      created.push(data)
      status = data.userid === 'taken' ? 409 : 201
      body = status === 409 ? { error: { code: 'userid_taken', message: 'Already taken.' } } : { ...data, id: crypto.randomUUID(), disabled: false }
    } else if (path === '/api/admin/users') body = { users: [] }
    return new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } })
  }))
  render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><RouterProvider router={createMemoryRouter([{ path: '*', element: <App /> }], { initialEntries: ['/admin/users/bulk'] })} /></QueryClientProvider>)
  const table = await screen.findByLabelText('一括作成の表にセルを貼り付け')
  fireEvent.paste(table, { clipboardData: { getData: () => 'first\tFirst\tstudent\t\ntaken\tSecond\twrong\t\nthird\tThird\tmanager\tmanual-password' } })
  const password = screen.getByLabelText('2行目 password')
  fireEvent.click(screen.getByRole('button', { name: 'Apply' }))
  expect(await screen.findByRole('alert')).toHaveProperty('textContent', 'role は student または manager にしてください。')
  const generated = (password as HTMLInputElement).value
  expect(generated).toMatch(/^[a-zA-Z0-9]{6}-[a-zA-Z0-9]{6}-[a-zA-Z0-9]{6}$/)
  expect(created).toHaveLength(0)
  expect(blobs).toHaveLength(0)
  fireEvent.change(screen.getByLabelText('2行目 role'), { target: { value: 'student' } })
  fireEvent.click(screen.getByRole('button', { name: 'Apply' }))
  expect(await screen.findByText('作成済み 2 / 3 件')).toBeDefined()
  expect(created.map((row) => row.userid)).toEqual(['first', 'taken', 'third'])
  expect(screen.getByLabelText('1行目 userid')).toHaveProperty('disabled', true)
  expect(screen.getByRole('button', { name: '元に戻す' })).toHaveProperty('disabled', true)
  fireEvent.paste(table, { clipboardData: { getData: () => 'overwrite' } })
  expect(screen.getByLabelText('1行目 userid')).toHaveProperty('value', 'first')
  fireEvent.keyDown(table, { key: 'Delete' })
  expect(screen.getByLabelText('2行目 userid')).toHaveProperty('value', 'taken')
  expect(password).toHaveProperty('value', generated)
  const firstCSV = await blobs[0].text()
  expect(firstCSV).toContain('\r\n,,,\r\nthird,Third,manager,manual-password\r\n')
  fireEvent.change(screen.getByLabelText('2行目 userid'), { target: { value: 'second' } })
  fireEvent.click(screen.getByRole('button', { name: 'Apply' }))
  expect(await screen.findByText('作成済み 3 / 3 件')).toBeDefined()
  expect(created.map((row) => row.userid)).toEqual(['first', 'taken', 'third', 'second'])
  expect(created[3].password).toBe(generated)
  expect(await blobs[1].text()).toContain(`second,Second,student,${generated}\r\nthird,Third,manager,manual-password`)
  const unload = new Event('beforeunload', { cancelable: true })
  window.dispatchEvent(unload)
  expect(unload.defaultPrevented).toBe(true)
  fireEvent.click(screen.getByRole('link', { name: 'User Accounts' }))
  expect(await screen.findByRole('dialog')).toBeDefined()
  fireEvent.click(screen.getByRole('button', { name: '戻る' }))
  expect(screen.getByLabelText('2行目 password')).toHaveProperty('value', generated)
  fireEvent.click(screen.getByRole('link', { name: 'User Accounts' }))
  fireEvent.click(await screen.findByRole('button', { name: '離れる' }))
  await waitFor(() => expect(screen.queryByRole('heading', { name: 'ユーザー作成（一括）' })).toBeNull())
  fireEvent.click(await screen.findByRole('link', { name: '一括作成' }))
  expect(await screen.findByLabelText('1行目 userid')).toHaveProperty('value', '')
})

test('spreadsheet selection, paste, clear and history work from an empty table', async () => {
  vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify({ id: crypto.randomUUID(), userid: 'admin', name: 'Admin', role: 'admin' }), { headers: { 'Content-Type': 'application/json' } })))
  render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><RouterProvider router={createMemoryRouter([{ path: '*', element: <App /> }], { initialEntries: ['/admin/users/bulk'] })} /></QueryClientProvider>)
  const table = await screen.findByLabelText('一括作成の表にセルを貼り付け')
  const cell = (row: number, column: string) => screen.getByLabelText(`${row}行目 ${column}`)
  expect(screen.queryByLabelText('選択範囲')).toBeNull()
  expect(screen.getAllByRole('columnheader').map((header) => header.textContent)).toEqual(['行', 'userid', 'username', 'role', 'password', '状態'])
  const paste = (target: HTMLElement, text: string) => fireEvent.paste(target, { clipboardData: { getData: () => text } })
  expect(screen.getByRole('button', { name: 'Apply' })).toHaveProperty('disabled', true)
  paste(table, Array.from({ length: 8 }, (_, i) => `s${i}\tName ${i}\tstudent\tpassword${i}`).join('\n'))
  fireEvent.mouseDown(cell(3, 'username'))
  paste(cell(3, 'username'), '佐藤\tstudent\n鈴木\tmanager\n高橋\tstudent')
  expect(screen.getAllByRole('gridcell', { selected: true })).toHaveLength(6)
  expect(cell(3, 'username').closest('td')?.getAttribute('aria-selected')).toBe('true')
  expect(cell(5, 'role').closest('td')?.getAttribute('aria-selected')).toBe('true')
  expect(cell(3, 'username')).toHaveProperty('value', '佐藤')
  expect(cell(5, 'role')).toHaveProperty('value', 'student')
  expect(cell(3, 'userid')).toHaveProperty('value', 's2')
  expect(cell(5, 'password')).toHaveProperty('value', 'password4')
  expect(cell(9, 'userid')).toHaveProperty('value', '')
  fireEvent.keyDown(table, { key: 'Delete' })
  expect(cell(3, 'username')).toHaveProperty('value', '')
  expect(cell(5, 'role')).toHaveProperty('value', '')
  fireEvent.keyDown(table, { key: 'z', metaKey: true })
  expect(cell(3, 'username')).toHaveProperty('value', '佐藤')
  fireEvent.click(screen.getByRole('button', { name: '元に戻す' }))
  expect(cell(3, 'username')).toHaveProperty('value', 'Name 2')
  fireEvent.keyDown(table, { key: 'y', ctrlKey: true })
  expect(cell(3, 'username')).toHaveProperty('value', '佐藤')
  fireEvent.mouseDown(cell(3, 'username'))
  fireEvent.keyDown(table, { key: 'ArrowRight', shiftKey: true })
  fireEvent.keyDown(table, { key: 'ArrowDown', shiftKey: true })
  expect(screen.getAllByRole('gridcell', { selected: true })).toHaveLength(4)
  expect(cell(4, 'role').closest('td')?.getAttribute('aria-selected')).toBe('true')
  paste(table, 'Only one')
  expect(cell(3, 'username')).toHaveProperty('value', 'Only one')
  expect(cell(4, 'username')).toHaveProperty('value', '鈴木')
  fireEvent.mouseDown(cell(1, 'password'))
  paste(table, 'too\twide')
  expect(screen.getByRole('alert').textContent).toContain('最終列（password）')
  expect(cell(1, 'password')).toHaveProperty('value', 'password0')
  fireEvent.mouseDown(cell(1, 'username'))
  fireEvent.doubleClick(cell(1, 'username'))
  fireEvent.change(cell(1, 'username'), { target: { value: 'Edit' } })
  fireEvent.change(cell(1, 'username'), { target: { value: 'Edited' } })
  fireEvent.blur(cell(1, 'username'))
  fireEvent.click(screen.getByRole('button', { name: '元に戻す' }))
  expect(cell(1, 'username')).toHaveProperty('value', 'Name 0')
  expect(screen.getByRole('button', { name: 'やり直す' })).toHaveProperty('disabled', false)
  paste(table, 'New')
  expect(screen.getByRole('button', { name: 'やり直す' })).toHaveProperty('disabled', true)
  fireEvent.mouseDown(cell(10, 'userid'))
  paste(table, Array.from({ length: 12 }, (_, i) => 'extra' + i).join('\n'))
  expect(screen.getAllByRole('gridcell', { selected: true })).toHaveLength(12)
  fireEvent.click(screen.getByRole('button', { name: '元に戻す' }))
  expect(screen.getAllByRole('gridcell', { selected: true })).toHaveLength(1)
  expect(cell(10, 'userid')).toHaveProperty('tabIndex', 0)
})

test('row context menu inserts around a selection, deletes whole rows and supports history', async () => {
  vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify({ id: crypto.randomUUID(), userid: 'admin', name: 'Admin', role: 'admin' }), { headers: { 'Content-Type': 'application/json' } })))
  render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><RouterProvider router={createMemoryRouter([{ path: '*', element: <App /> }], { initialEntries: ['/admin/users/bulk'] })} /></QueryClientProvider>)
  const table = await screen.findByLabelText('一括作成の表にセルを貼り付け')
  const cell = (row: number, column = 'userid') => screen.getByLabelText(`${row}行目 ${column}`)
  fireEvent.paste(table, { clipboardData: { getData: () => 'a\tA\nb\tB\nc\tC\nd\tD' } })
  const selectMiddle = () => {
    fireEvent.mouseDown(cell(3, 'username'))
    fireEvent.keyDown(table, { key: 'ArrowUp', shiftKey: true })
    fireEvent.contextMenu(cell(2, 'username'))
  }
  selectMiddle()
  fireEvent.click(await screen.findByRole('menuitem', { name: '前に行を挿入' }))
  expect(cell(1)).toHaveProperty('value', 'a')
  expect(cell(2)).toHaveProperty('value', '')
  expect(cell(3)).toHaveProperty('value', 'b')
  expect(cell(5, 'username')).toHaveProperty('value', 'D')
  fireEvent.click(screen.getByRole('button', { name: '元に戻す' }))
  selectMiddle()
  fireEvent.click(await screen.findByRole('menuitem', { name: '後ろに行を挿入' }))
  expect(cell(3)).toHaveProperty('value', 'c')
  expect(cell(4)).toHaveProperty('value', '')
  expect(cell(5)).toHaveProperty('value', 'd')
  fireEvent.click(screen.getByRole('button', { name: '元に戻す' }))
  selectMiddle()
  fireEvent.click(await screen.findByRole('menuitem', { name: '選択した行を削除' }))
  expect(cell(1)).toHaveProperty('value', 'a')
  expect(cell(2)).toHaveProperty('value', 'd')
  expect(cell(2, 'username')).toHaveProperty('value', 'D')
  expect(cell(3)).toHaveProperty('value', '')
  fireEvent.click(screen.getByRole('button', { name: '元に戻す' }))
  expect(cell(2)).toHaveProperty('value', 'b')
  fireEvent.click(screen.getByRole('button', { name: 'やり直す' }))
  expect(cell(2)).toHaveProperty('value', 'd')
  // Right-clicking outside the selection targets only that row, including blank display rows.
  fireEvent.contextMenu(cell(10))
  fireEvent.click(await screen.findByRole('menuitem', { name: '後ろに行を挿入' }))
  expect(cell(11)).toHaveProperty('value', '')
  expect(cell(11).closest('td')?.getAttribute('aria-selected')).toBe('true')
  expect(cell(2)).toHaveProperty('value', 'd')
})

test('blank display rows do not trigger creation or navigation guards and busy operations cannot edit', async () => {
  let finish: (() => void) | undefined
  const posted: string[] = []
  vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:test')
  vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {})
  vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
  vi.stubGlobal('fetch', vi.fn(async (request: Request) => {
    if (request.method === 'POST') {
      const body = await request.json()
      posted.push(body.userid)
      await new Promise<void>((resolve) => { finish = resolve })
      return new Response(JSON.stringify({ ...body, id: crypto.randomUUID(), disabled: false }), { status: 201, headers: { 'Content-Type': 'application/json' } })
    }
    return new Response(JSON.stringify({ id: crypto.randomUUID(), userid: 'admin', name: 'Admin', role: 'admin' }), { headers: { 'Content-Type': 'application/json' } })
  }))
  render(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><RouterProvider router={createMemoryRouter([{ path: '*', element: <App /> }], { initialEntries: ['/admin/users/bulk'] })} /></QueryClientProvider>)
  const table = await screen.findByLabelText('一括作成の表にセルを貼り付け')
  fireEvent.click(screen.getByRole('button', { name: '＋ 行を追加' }))
  const unload = new Event('beforeunload', { cancelable: true })
  window.dispatchEvent(unload)
  expect(unload.defaultPrevented).toBe(false)
  fireEvent.mouseDown(screen.getByLabelText('3行目 userid'))
  fireEvent.paste(table, { clipboardData: { getData: () => 'one\tOne\tstudent' } })
  fireEvent.click(screen.getByRole('button', { name: 'Apply' }))
  await waitFor(() => expect(posted).toEqual(['one']))
  fireEvent.paste(table, { clipboardData: { getData: () => 'changed' } })
  fireEvent.keyDown(table, { key: 'Delete' })
  fireEvent.keyDown(table, { key: 'z', ctrlKey: true })
  expect(screen.getByLabelText('3行目 userid')).toHaveProperty('value', 'one')
  expect(screen.getByLabelText('3行目 userid')).toHaveProperty('disabled', true)
  finish?.()
  expect(await screen.findByText('作成済み 1 / 1 件')).toBeDefined()
  expect(screen.getByRole('button', { name: '元に戻す' })).toHaveProperty('disabled', true)
  fireEvent.mouseDown(screen.getByLabelText('2行目 username'))
  fireEvent.keyDown(table, { key: 'ArrowDown', shiftKey: true })
  fireEvent.contextMenu(screen.getByLabelText('2行目 username'))
  expect((await screen.findByRole('menuitem', { name: '選択した行を削除' })).getAttribute('aria-disabled')).toBe('true')
  fireEvent.click(screen.getByRole('menuitem', { name: '選択した行を削除' }))
  expect(screen.getByLabelText('3行目 userid')).toHaveProperty('value', 'one')
})
