apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../e2e
patches:
  - target:
      kind: Ingress
      name: dsa
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: e2e.localhost
      - op: remove
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.tls
