services:
  frontend:
    build: ./dsa-frontend
    volumes:
      - ./dsa-frontend:/app
      # ホストの./dsa-front/node_modulesをコンテナ内の/app/node_modulesに反映させないために、
      # コンテナ内の/app/node_modulesを専用のボリュームにマウント
      - frontend-node_modules:/app/node_modules
    entrypoint: [ "sh", "-c", "npm install && npm start" ]

  backend:
    depends_on:
      db:
        condition: service_healthy
    build: ./dsa-backend
    ports:
      # ホストのlocalhost:8000番ポートをコンテナの8000番ポートにマッピング
      # 注) Swagger UIにアクセスし、APIをテストするために開放している。
      #     WebUIからアクセスする場合は開放しなくても良い。
      - "127.0.0.1:8000:8000"
    volumes:
      - ./dsa-backend:/app
      # ホストの./dsa-back/.venvをコンテナ内の/app/.venvに反映させないために、
      # コンテナ内の/app/.venvをAnonymous Volumeとしてマウント
      - ./upload:/upload
      - ./resource:/resource
    environment:
      TZ: Asia/Tokyo
      ACCESS_TOKEN_EXPIRE_MINUTES: 180
    secrets:
      - db_app_password
      - admin_info_json
    restart: always

  judge:
    depends_on:
      db:
        condition: service_healthy
    build: ./dsa-judgeserver
    ports:
      # ホストのlocalhost:8080番ポートをコンテナの8080番ポートにマッピング
      # 注意) デフォルトだとグローバルIPアドレスからアクセスできてしまうため，
      #       ホストのlocalhostのみにマッピングする
      - "127.0.0.1:8080:8080"
    volumes:
      # ホスト環境のDockerサービスにアクセスするためのDockerソケットのマウント
      # 注) ホスト環境がUbuntuである必要あり
      - /var/run/docker.sock:/var/run/docker.sock
      # ソースコードのマウント
      - ./dsa-judgeserver:/app
      # ホストの./dsa-judge/.venvをコンテナ内の/app/.venvに反映させないために、
      # コンテナ内の/app/.venvをAnonymous Volumeとしてマウント
      - /app/.venv
      # アップロードされたファイル用のディレクトリのマウント
      - ./upload:/upload
      # リソースディレクトリ(テストケース、サンプルプログラム等)のマウント
      - ./resource:/resource
      # ログディレクトリのマウント
      - ./logs/dsa-judgeserver:/logs
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: dsa
      DATABASE_USER: dsa
      DATABASE_PASSWORD: dsa-jikken
      DATABASE_PORT: 3306
      DOCKER_HOST: unix:///var/run/docker.sock
      TZ: Asia/Tokyo

  nginx:
    image: nginx:latest
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/log/:/var/log/nginx/:rw
    restart: always
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started

  db:
    build: ./dsa-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      # Just for debugging of backend, need to delete in production.
      - "127.0.0.1:5432:5432"
    secrets:
      - db_app_password
      - db_root_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_root_password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dsa-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # バックアップのための、ダンプファイル共有ディレクトリ
      - ./backup:/backup

  adminer:
    image: adminer:5.3.0
    restart: always
    ports:
      - "127.0.0.1:18080:8080"
    depends_on:
      db:
        condition: service_started

volumes:
  db-data:
  frontend-node_modules:


secrets:
  db_app_password:
    file: ./config/db_app_password.txt
  db_root_password:
    file: ./config/db_root_password.txt
  admin_info_json:
    file: ./config/admin.json
