CREATE TABLE user_accounts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    userid text NOT NULL UNIQUE,
    name text NOT NULL,
    role text NOT NULL CHECK (role IN ('student', 'manager', 'admin')),
    password_hash text,
    disabled_at timestamptz,
    is_system boolean NOT NULL DEFAULT false,
    CONSTRAINT login_capability CHECK (
        (is_system AND password_hash IS NULL) OR (NOT is_system AND password_hash IS NOT NULL)
    ),
    display_order bigint GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT user_accounts_display_order_key
        UNIQUE (display_order) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_account_id uuid NOT NULL REFERENCES user_accounts(id),
    token_hash bytea NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);
CREATE INDEX sessions_user_account_created_idx ON sessions (user_account_id, created_at, id);

CREATE TABLE projects (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    resource_id text NOT NULL UNIQUE,
    name text NOT NULL,
    latest_version_id uuid NOT NULL,
    published_at timestamptz,
    deadline timestamptz,
    CONSTRAINT projects_schedule_check CHECK (published_at <= deadline),
    display_order bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT projects_display_order_key
        UNIQUE (display_order) DEFERRABLE INITIALLY IMMEDIATE
);

-- Versions are immutable snapshots; corrections insert a new version.
CREATE TABLE project_versions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL REFERENCES projects(id),
    version text NOT NULL CHECK (version ~ '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'),
    resource_json json NOT NULL,
    registered_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, version),
    UNIQUE (project_id, id)
);

-- Preallocate both UUIDs, insert the Project, then its first Version in one
-- transaction. At commit, latest must exist and belong to this Project.
ALTER TABLE projects ADD CONSTRAINT projects_latest_version_fkey
    FOREIGN KEY (id, latest_version_id) REFERENCES project_versions(project_id, id)
    DEFERRABLE INITIALLY DEFERRED;
