CREATE TABLE user_accounts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    userid text NOT NULL UNIQUE,
    name text NOT NULL,
    role text NOT NULL CHECK (role IN ('student', 'manager', 'admin')),
    password_hash text NOT NULL,
    disabled_at timestamptz,
    display_order bigint GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT user_accounts_display_order_key
        UNIQUE (display_order) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_account_id uuid NOT NULL REFERENCES user_accounts(id),
    token_hash bytea NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);
CREATE INDEX sessions_user_account_created_idx ON sessions (user_account_id, created_at, id);

CREATE TABLE projects (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    resource_id text NOT NULL UNIQUE,
    name text NOT NULL,
    latest_version_id uuid NOT NULL,
    published_at timestamptz,
    deadline timestamptz,
    CONSTRAINT projects_schedule_check CHECK (published_at <= deadline),
    display_order bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT projects_display_order_key
        UNIQUE (display_order) DEFERRABLE INITIALLY IMMEDIATE
);

-- Versions are immutable snapshots; corrections insert a new version.
CREATE TABLE project_versions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id uuid NOT NULL REFERENCES projects(id),
    version text NOT NULL CHECK (version ~ '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'),
    resource_json json NOT NULL,
    registered_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, version),
    UNIQUE (project_id, id)
);

-- Preallocate both UUIDs, insert the Project, then its first Version in one
-- transaction. At commit, latest must exist and belong to this Project.
ALTER TABLE projects ADD CONSTRAINT projects_latest_version_fkey
    FOREIGN KEY (id, latest_version_id) REFERENCES project_versions(project_id, id)
    DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE submissions (
    id uuid PRIMARY KEY DEFAULT uuidv7(),
    project_id uuid NOT NULL REFERENCES projects(id),
    kind text NOT NULL CHECK (kind IN ('validation', 'evaluation')),
    subject_user_id uuid NOT NULL REFERENCES user_accounts(id),
    content_hash text NOT NULL,
    original_submitted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT submissions_original_submitted_at_check CHECK (
        (kind = 'validation' AND original_submitted_at IS NULL)
        OR (kind = 'evaluation' AND original_submitted_at IS NOT NULL)
    ),
    UNIQUE (project_id, kind, subject_user_id, content_hash),
    UNIQUE (project_id, id)
);

CREATE TABLE submission_files (
    submission_id uuid NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    path text NOT NULL,
    content bytea NOT NULL,
    PRIMARY KEY (submission_id, path)
);

CREATE TABLE requests (
    id uuid PRIMARY KEY DEFAULT uuidv7(),
    -- Composite foreign keys keep the Submission and Version in one Project.
    project_id uuid NOT NULL,
    submission_id uuid NOT NULL,
    version_id uuid NOT NULL,
    requested_by uuid NOT NULL REFERENCES user_accounts(id),
    requested_at timestamptz NOT NULL DEFAULT now(),
    state text NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending', 'running', 'retrying', 'completed')),
    status text CHECK (status IN ('IE', 'CE', 'OLE', 'MLE', 'TLE', 'RE', 'WA', 'SKIP', 'AC')),
    lease_owner uuid,
    lease_expires_at timestamptz,
    -- Increment on each attempt; also serves as the execution generation.
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count BETWEEN 0 AND 3),
    attempt_started_at timestamptz,
    duration_ms bigint CHECK (duration_ms >= 0),
    error text,
    CONSTRAINT requests_completed_status_check CHECK ((state = 'completed') = (status IS NOT NULL)),
    CONSTRAINT requests_lease_check CHECK (
        (state = 'running' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        OR (state <> 'running' AND lease_owner IS NULL AND lease_expires_at IS NULL)
    ),
    CONSTRAINT requests_state_attempt_count_check CHECK (
        (state = 'pending' AND attempt_count = 0)
        OR (state <> 'pending' AND attempt_count > 0)
    ),
    FOREIGN KEY (project_id, submission_id) REFERENCES submissions(project_id, id) ON DELETE CASCADE,
    FOREIGN KEY (project_id, version_id) REFERENCES project_versions(project_id, id)
);

CREATE TABLE workflow_results (
    request_id uuid NOT NULL
        REFERENCES requests(id) ON DELETE CASCADE,
    workflow_id text NOT NULL,
    status text NOT NULL CHECK (
            status IN ('IE', 'CE', 'OLE', 'MLE', 'TLE', 'RE', 'WA', 'SKIP', 'AC')
    ),
    duration_ms bigint NOT NULL CHECK (duration_ms >= 0),
    details jsonb NOT NULL,
    PRIMARY KEY (request_id, workflow_id),
    CHECK (jsonb_typeof(details) = 'object')
);

CREATE TABLE artifacts (
    id uuid PRIMARY KEY DEFAULT uuidv7(),
    request_id uuid NOT NULL
        REFERENCES requests(id) ON DELETE CASCADE,
    attempt_count integer NOT NULL CHECK (attempt_count > 0),
    workflow_id text NOT NULL,
    job_id text NOT NULL,
    name text NOT NULL,
    content bytea,
    error text,
    CONSTRAINT artifacts_capture_result_check CHECK (
        (content IS NOT NULL AND error IS NULL)
        OR (content IS NULL AND error IS NOT NULL AND error <> '')
    ),

    UNIQUE (request_id, attempt_count, workflow_id, job_id, name)
);

CREATE INDEX requests_submission_id_idx ON requests (submission_id);
CREATE INDEX requests_waiting_idx ON requests (requested_at, id)
    WHERE state IN ('pending', 'retrying');
CREATE INDEX requests_lease_expires_at_idx ON requests (lease_expires_at, id)
    WHERE state = 'running';
