apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dsa.fullname" . }}-datastore
  labels:
    {{- include "dsa.labels" . | nindent 4 }}
    app.kubernetes.io/component: datastore
type: Opaque
stringData:
  postgres-username: {{ required "postgresql.auth.username is required" .Values.postgresql.auth.username | quote }}
  postgres-password: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password | quote }}
  postgres-database: {{ required "postgresql.auth.database is required" .Values.postgresql.auth.database | quote }}
  redis-password: {{ required "redis.auth.password is required" .Values.redis.auth.password | quote }}
  database-url: {{ printf "postgres://%s:%s@%s-postgresql:5432/%s?sslmode=disable" (.Values.postgresql.auth.username | urlquery | replace "+" "%20") (.Values.postgresql.auth.password | urlquery | replace "+" "%20") (include "dsa.fullname" .) (.Values.postgresql.auth.database | urlquery | replace "+" "%20") | quote }}
  redis-url: {{ printf "redis://:%s@%s-redis:6379/0" (.Values.redis.auth.password | urlquery | replace "+" "%20") (include "dsa.fullname" .) | quote }}
