apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dsa.fullname" . }}-redis
  labels:
    {{- include "dsa.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dsa.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "dsa.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command: ["sh", "-c"]
          args: ['exec redis-server --save "" --appendonly no --requirepass "$REDIS_PASSWORD"']
          ports:
            - name: redis
              containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dsa.fullname" . }}-datastore
                  key: redis-password
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ include "dsa.fullname" . }}-datastore
                  key: redis-password
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
