apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsa-dev
resources:
  - namespace.yaml
  - ../../base
  - datastore-secret.yaml
images:
  - name: dsa-backend
    newTag: dev
  - name: dsa-frontend
    newTag: dev
patches:
  - target:
      kind: Deployment
      name: dsa-(backend|frontend)
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: PersistentVolumeClaim
      name: dsa-postgresql
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: local-path
