basePath: /api
definitions:
  handler.userLoginRequest:
    properties:
      password:
        type: string
      userid:
        type: string
    required:
    - password
    - userid
    type: object
  handler.userLoginResponse:
    properties:
      token:
        type: string
    type: object
  utils.Error:
    properties:
      errors:
        additionalProperties: true
        type: object
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the API for the DSA Backend application.
  title: DSA Backend API
  version: 0.0.1
paths:
  /login:
    post:
      consumes:
      - application/json
      description: User login with user ID and password. Returns a JWT token if successful.
      parameters:
      - description: User login info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.userLoginRequest'
      responses:
        "200":
          description: Login successful. Returns a JWT token.
          schema:
            $ref: '#/definitions/handler.userLoginResponse'
        "400":
          description: Bad request. This error occurs if the user ID or password is
            missing or incorrect.
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal server error. This error occurs if there is an issue
            with the database or password hashing.
          schema:
            type: string
      summary: User Login
      tags:
      - user
swagger: "2.0"
