basePath: /api
definitions:
  handler.userLoginResponse:
    properties:
      access_token:
        type: string
      token_type:
        type: string
      user:
        $ref: '#/definitions/handler.userResponse'
    type: object
  handler.userResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  utils.Error:
    properties:
      errors:
        additionalProperties: true
        type: object
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the API for the DSA Backend application.
  title: DSA Backend API
  version: 0.0.1
paths:
  /currentUser/me:
    get:
      description: Get current user information from JWT token
      responses:
        "200":
          description: Current user information
          schema:
            $ref: '#/definitions/handler.userResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - OAuth2Password:
        - me
      summary: Get current user information
      tags:
      - user
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: User login with user ID and password. Returns a JWT token if successful.
      parameters:
      - description: User ID
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: Login successful. Returns a JWT token.
          schema:
            $ref: '#/definitions/handler.userLoginResponse'
        "400":
          description: Bad request. This error occurs if the user ID or password is
            missing or incorrect.
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal server error. This error occurs if there is an issue
            with the database or password hashing.
          schema:
            type: string
      summary: User Login
      tags:
      - user
securityDefinitions:
  OAuth2Password:
    flow: password
    scopes:
      admin: Grants any rights related to admin user
      manager: Grants any rights related to manager user
      me: Grants any rights related to the current user
    tokenUrl: /api/login
    type: oauth2
swagger: "2.0"
