/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** userid と password でログインする */
        post: operations["createSession"];
        /** 現在のセッションからログアウトする */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在の User Account を返す */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all non-System User Accounts, including disabled accounts, in persisted display order */
        get: operations["listUserAccounts"];
        put?: never;
        /** Create a User Account at the end of the global display order */
        post: operations["createUserAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atomically update supplied fields of a User Account
         * @description Userid is immutable. Last-write-wins; supplying existing values succeeds.
         *     System Accounts cannot be modified (cannot_modify_system_account).
         *     An Admin cannot change their own Role or disable themselves (cannot_modify_self).
         *     Password replacement and transitions to disabled delete all affected sessions
         *     in the same transaction. Other changes retain sessions. Repeated disabling
         *     preserves the original disabled timestamp; re-enabling retains the password
         *     unless a replacement is supplied. Display order is preserved.
         */
        patch: operations["updateUserAccount"];
        trace?: never;
    };
    "/api/users/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Save the global User Account display order (Admin only)
         * @description Supply every non-System User Account ID exactly once, including disabled
         *     accounts. Missing, duplicate, unknown, or System Account IDs return
         *     422 user_ids_mismatch without changing the order.
         *     The saved order drives the Admin list and future roster views.
         */
        patch: operations["reorderUserAccounts"];
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects in display order
         * @description Students see only published Projects; Managers and Admins see all. Workflow summaries come from the latest Version. No private Job or Resource data is exposed.
         */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the latest Project with all Workflow descriptions
         * @description Students see only published Projects; Managers and Admins see all.
         *     Always returns the latest imported Version. Workflows are sorted by ID
         *     lexicographically. No Jobs, presets or expected outputs are exposed.
         *     Markdown attachments are not supported.
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Save all Project schedules and display order
         * @description Supply every Project ID exactly once. The array order becomes the display
         *     order. Both nullable timestamps are required; if set, published_at must
         *     not exceed deadline. All changes commit atomically. Last save wins.
         *     Missing, duplicate, or unknown IDs return project_ids_mismatch.
         *     An empty array is accepted only when no Projects exist.
         */
        patch: operations["updateProjects"];
        trace?: never;
    };
    "/api/admin/resource-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a Resource Version from the configured GitHub repository
         * @description Synchronously fetch and validate a Resource, then atomically save its
         *     immutable Version and update the Project title and latest Version.
         *     First import creates an unpublished Project with no deadline at the end
         *     of the list. Updates preserve schedule and order. Equal Versions return
         *     changed=false without accessing GitHub; older Versions are rejected.
         *     Repository, commit and image overrides are not accepted. No rejudging occurs.
         */
        post: operations["importResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProjectUpdate: {
            /** Format: uuid */
            id: string;
            published_at: components["schemas"]["NullableTimestamp"];
            deadline: components["schemas"]["NullableTimestamp"];
        };
        /**
         * Format: date-time
         * @description RFC 3339 UTC or null
         */
        NullableTimestamp: string | null;
        /** @enum {string} */
        Status: "AC" | "WA" | "TLE" | "MLE" | "RE" | "OLE" | "IE";
        NullableStatus: components["schemas"]["Status"] | null;
        Project: {
            /** Format: uuid */
            id: string;
            resource_id: string;
            name: string;
            /** Format: uuid */
            latest_version_id: string;
            latest_version: string;
            /** Format: int64 */
            display_order: number;
            published_at: components["schemas"]["NullableTimestamp"];
            deadline: components["schemas"]["NullableTimestamp"];
            workflows: {
                id: string;
                name: string;
            }[];
            my_result: components["schemas"]["MyResult"];
        };
        /** @description Latest own validation Request and its Submission, across Versions. Currently null until Submission/Request APIs are implemented. */
        MyResult: {
            /** Format: uuid */
            submission_id: string;
            /** @description Full normalized file tree hash (Normalized Submission Identity). Clients abbreviate the digest for display. */
            content_hash: string;
            /** Format: date-time */
            uploaded_at: string;
            request: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                version_id: string;
                version: string;
                /** @enum {string} */
                state: "pending" | "queued" | "running" | "completed";
                status: components["schemas"]["NullableStatus"];
                workflows: {
                    id: string;
                    /** @description Workflow name from the Request's pinned Version, not the latest Project Version. */
                    name: string;
                    status: components["schemas"]["NullableStatus"];
                    /**
                     * Format: int64
                     * @description Sum of executed Step durations in this Workflow, including compilation. Unexecuted Steps are excluded. Null until the Request completes or if timing is unavailable.
                     */
                    duration_ms: number | null;
                }[];
            };
        } | null;
        ProjectDetail: {
            /** Format: uuid */
            id: string;
            resource_id: string;
            name: string;
            /** Format: uuid */
            latest_version_id: string;
            latest_version: string;
            /** Format: int64 */
            display_order: number;
            published_at: components["schemas"]["NullableTimestamp"];
            deadline: components["schemas"]["NullableTimestamp"];
            /** @description Display-only guidance preserving Resource text and order. Empty when unspecified; not used to validate submissions. */
            required_files: string[];
            workflows: {
                id: string;
                name: string;
                /** @description Inline Markdown from the snapshot; empty when unspecified. No attachment serving or URL rewriting. */
                description_markdown: string;
            }[];
            my_result: components["schemas"]["MyResult"];
        };
        CreateSessionRequest: {
            userid: string;
            password: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            userid: string;
            name: string;
            /** @enum {string} */
            role: "student" | "manager" | "admin";
        };
        /**
         * @description Roles assignable through user management; the sole Admin is provisioned separately.
         * @enum {string}
         */
        AssignableUserRole: "student" | "manager";
        /** @enum {string} */
        UserRole: "student" | "manager" | "admin";
        /** @description Immutable, case-sensitive, without trimming or normalization */
        Userid: string;
        /** @description 1–64 Unicode characters; no control characters or whitespace-only values; no trimming or normalization */
        DisplayName: string;
        /** @description Unicode characters, without trimming, normalization, or character-class rules; confirmation is frontend-only */
        NewPassword: string;
        UserAccount: {
            /** Format: uuid */
            id: string;
            userid: string;
            name: string;
            role: components["schemas"]["UserRole"];
            disabled: boolean;
        };
        CreateUserAccountRequest: {
            userid: components["schemas"]["Userid"];
            name: components["schemas"]["DisplayName"];
            role: components["schemas"]["AssignableUserRole"];
            password: components["schemas"]["NewPassword"];
        };
        UpdateUserAccountRequest: {
            name?: components["schemas"]["DisplayName"];
            role?: components["schemas"]["AssignableUserRole"];
            password?: components["schemas"]["NewPassword"];
            disabled?: boolean;
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description バリデーション失敗 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 認証情報が無効 */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未認証 */
        Unauthorized: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description サーバー内部エラー */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Admin Role required */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description User Account not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description userid_taken (exact duplicate), cannot_modify_self, or cannot_modify_system_account */
        UserConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        SessionCookie: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description ログインした User Account */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["InvalidCredentials"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                "__Host-dsa_session"?: components["parameters"]["SessionCookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description セッションを削除した（セッションがなくても成功） */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 現在の User Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listUserAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All User Accounts, without pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users: components["schemas"]["UserAccount"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createUserAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserAccountRequest"];
            };
        };
        responses: {
            /** @description Created User Account */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["UserConflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    updateUserAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserAccountRequest"];
            };
        };
        responses: {
            /** @description Updated User Account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["UserConflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    reorderUserAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_ids: string[];
                };
            };
        };
        responses: {
            /** @description Global display order saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description user_ids_mismatch for an incomplete or incorrect set; validation_failed for malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All visible Projects, without pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: components["schemas"]["Project"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    getProject: {
        parameters: {
            query?: {
                /** @description Not accepted; any supplied value returns version_not_allowed. */
                version_id?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest visible Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Project not found or not visible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description version_not_allowed or validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    updateProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    projects: components["schemas"]["ProjectUpdate"][];
                };
            };
        };
        responses: {
            /** @description Schedules and order saved; reload GET /api/projects */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description project_ids_mismatch or validation_failed; nothing is changed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    importResource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    resource_id: string;
                    /** @description Formal vMAJOR.MINOR.PATCH only; validated by the handler to return invalid_resource_version */
                    version: string;
                };
            };
        };
        responses: {
            /** @description Committed import or unchanged current Version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        project_id: string;
                        /** Format: uuid */
                        version_id: string;
                        resource_id: string;
                        version: string;
                        changed: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description resource_version_not_found (not in index) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description older_resource_version */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description invalid_resource_version, invalid_resource, resource_hash_mismatch, or validation_failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
            /** @description resource_source_unavailable (including authentication, rate limit, and download failures); upstream bodies and credentials are never returned */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
