apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsa-postgresql
  labels:
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
