apiVersion: v1
kind: ServiceAccount
metadata:
  name: dsa-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dsa-postgresql
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dsa-redis
