apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dsa-backend-secrets
spec:
  provider: openbao
  parameters:
    roleName: dsa-prod-backend
    audience: openbao
    baoAddress: https://openbao.openbao.svc:8200
    objects: |
      - objectName: postgres-password
        secretPath: kv/data/dsa/prod/postgresql
        secretKey: password
        filePermission: 384
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dsa-postgresql-secrets
spec:
  provider: openbao
  parameters:
    roleName: dsa-prod-postgresql
    audience: openbao
    baoAddress: https://openbao.openbao.svc:8200
    objects: |
      - objectName: postgres-password
        secretPath: kv/data/dsa/prod/postgresql
        secretKey: password
        filePermission: 384
