# Shared by OrbStack and k3d; both provide LoadBalancer services.
ingressClass:
  enabled: false
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: false
service:
  type: LoadBalancer
ports:
  web:
    exposedPort: 80
  websecure:
    expose:
      default: false
api:
  dashboard: false
