[package]
name = "watchdog"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["process", "signal"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
