apiVersion: batch/v1
kind: Job
metadata:
  name: dsa-e2e
  labels:
    app.kubernetes.io/component: e2e
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dsa
        app.kubernetes.io/component: e2e
    spec:
      restartPolicy: Never
      containers:
        - name: e2e
          image: dsa-e2e:required
          imagePullPolicy: IfNotPresent
          env:
            - name: E2E_BASE_URL
              value: http://traefik.kube-system.svc.cluster.local
            - name: E2E_BROWSER_BASE_URL
              value: http://localhost
            - name: E2E_BROWSER_HOST_TARGET
              value: http://traefik.kube-system.svc.cluster.local
          resources: {}
